= Setup
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:sourcedir: .

[[_preinstall_requirements_and_prerequisites]]
== Pre-Install Requirements and Prerequisites


Ensure that the following requirements have been met before continuing with the install.

=== Hardware Requirements


The RA hardware requirements don't differ from the underlying {this-platform}
JAIN SLEE requirements, refer to its documentation for further information.

[[_software_prerequisites]]
=== Software Prerequisites


The RA requires {this-platform}
JAIN SLEE properly set.

[[_source_code]]
== {this-platform} JAIN SLEE {this-ra} Resource Adaptor Source Code



[[_release_source_building]]
=== Release Source Code Building


. {empty}
+
+
(((download)))
+

[IMPORTANT]
====
Git is used to manage Mobicents JAIN SLEE source code.
Instructions for downloading, installing and using Git can be found at http://git-scm.com/
====
+
Use Git to checkout a specific release source, the Git repository URL is {this-trunk-source-code-url}
, then switch to the specific release version, lets consider {this-version}
.
+

[source]
----

[usr]$ git clone  mobicents-jain-slee-
[usr]$ cd mobicents-jain-slee-
[usr]$ git checkout tags/
----
. {empty}
+
+
(((build)))
+

[IMPORTANT]
====
Maven 2.2.1 (or higher) is used to build the release.
Instructions for using Maven2, including install, can be found at http://maven.apache.org
====
+
Use Maven to build the deployable unit binary.
+

[source]
----

[usr]$ cd resources/
[usr]$ mvn install
----
+
Once the process finishes you should have the `deployable-unit` jar file in the [path]_target_
directory, if {this-platform}
JAIN SLEE is installed and environment variable JBOSS_HOME is pointing to its underlying {jee-platform} 
directory, then the deployable unit jar will also be deployed in the container.


[[_master_source_building]]
=== Development Master Source Building


Similar process as for <<_release_source_building>>
, the only change is the Git reference should be the ``master``.
The `git checkout tags/{this-version}` command should not be performed.
If already performed, the following should be used in order to switch back to the master:

[source]
----

[usr]$ git checkout master
----

[[_install]]
== Installing {this-platform} JAIN SLEE {this-ra} Resource Adaptor
(((install)))


To install the Resource Adaptor simply execute provided ant script [path]_build.xml_
 default target:

[source]
----

[usr]$ ant
----


The script will copy the RA deployable unit jar to the `default`{this-platform}
 JAIN SLEE server profile deploy directory, to deploy to another server profile use the argument ``-Dnode=``.

[[_uninstall]]
== Uninstalling {this-platform} JAIN SLEE {this-ra} Resource Adaptor
(((uninstall)))


To uninstall the Resource Adaptor simply execute provided ant script [path]_build.xml_``undeploy`` target:

[source]
----

[usr]$ ant undeploy
----


The script will delete the RA deployable unit jar from the `default`{this-platform}
 JAIN SLEE server profile deploy directory, to undeploy from another server profile use the argument ``-Dnode=``.

ifdef::backend-docbook[]
[index]
== Index
// Generated automatically by the DocBook toolchain.
endif::backend-docbook[]